import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BookOpen, BookOpenText, Cloud, CloudOff, Compass, FilePenLine, FolderOpen, History, ImagePlus, Keyboard, Library, LockKeyhole, Menu, MoreHorizontal, PenLine, Plus, RefreshCw, Save, Search, Send, Share2, Sparkles, Users, X } from 'lucide-react'
import './styles.css'
import CloseReading from './close-reading/CloseReading'

const API = '/api'
const userId = 'user-demo'
const api = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', 'x-user-id': userId, ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(payload.message || '请求失败'); Object.assign(error, payload, { status: response.status }); throw error } return payload }
const formatDate = value => new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value))

function App() {
  const [user, setUser] = useState(null); const [projects, setProjects] = useState([]); const [activeId, setActiveId] = useState(null); const [loading, setLoading] = useState(true); const [view, setView] = useState('workspace'); const [notice, setNotice] = useState(null); const [mobileNav, setMobileNav] = useState(false); const [showCreate, setShowCreate] = useState(false)
  const active = projects.find(p => p.id === activeId) || projects[0] || null
  const refresh = useCallback(async () => { setLoading(true); try { const [{ user }, { projects }] = await Promise.all([api('/me'), api('/projects')]); setUser(user); setProjects(projects); setActiveId(current => projects.some(p => p.id === current) ? current : projects[0]?.id || null) } catch (error) { setNotice({ type: 'error', text: error.message }) } finally { setLoading(false) } }, [])
  useEffect(() => { refresh() }, [refresh])
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(null), 5200); return () => clearTimeout(timer) }, [notice])
  const selectProject = id => { setActiveId(id); setView('workspace'); setMobileNav(false) }
  const handleCreated = project => { setProjects(list => [project, ...list]); setActiveId(project.id); setShowCreate(false); setView('workspace'); setNotice({ type: 'success', text: '项目已创建，工作台准备好了' }) }
  const updateProject = updated => setProjects(list => list.map(p => p.id === updated.id ? updated : p))
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'is-open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Sparkles size={16} /></span><span>Novelverse</span><button className="icon-btn close-mobile" onClick={() => setMobileNav(false)} aria-label="关闭导航"><X size={18} /></button></div>
      <div className="sidebar-user"><div className="avatar">{user?.initials || 'LZ'}</div><div><strong>{user?.name || '正在加载'}</strong><span>创作者空间</span></div><MoreHorizontal size={18} className="muted-icon" /></div>
      <nav className="primary-nav"><button className={view === 'workspace' ? 'active' : ''} onClick={() => { setView('workspace'); setMobileNav(false) }}><PenLine size={17} />工作台</button><button className={view === 'close-reading' ? 'active' : ''} onClick={() => { setView('close-reading'); setMobileNav(false) }}><BookOpenText size={17} />逐段精读</button><button className={view === 'projects' ? 'active' : ''} onClick={() => { setView('projects'); setMobileNav(false) }}><FolderOpen size={17} />我的项目 <span className="nav-count">{projects.length}</span></button><button onClick={() => setNotice({ type: 'info', text: '赏析空间正在整理中，稍后开放' })}><Library size={17} />赏析</button><button onClick={() => setNotice({ type: 'info', text: '历史记录将在下一阶段接入' })}><History size={17} />历史</button><button onClick={() => setNotice({ type: 'info', text: '共读功能正在准备中' })}><Users size={17} />共读</button></nav>
      <div className="sidebar-bottom"><div className="up-next"><span className="eyebrow">NEXT CHAPTER</span><strong>把灵感变成章节</strong><p>从一个项目开始，慢慢长出你的故事宇宙。</p><button onClick={() => setShowCreate(true)}>新建项目 <Plus size={15} /></button></div><div className="sidebar-footer"><span>v0.1 · 预览版</span><button aria-label="帮助" onClick={() => setNotice({ type: 'info', text: '快捷键：⌘/Ctrl + S 保存草稿' })}><Keyboard size={16} /></button></div></div>
    </aside>
    {mobileNav && <div className="scrim" onClick={() => setMobileNav(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="icon-btn menu-btn" onClick={() => setMobileNav(true)} aria-label="打开导航"><Menu size={20} /></button><div className="breadcrumbs"><span>你的空间</span><span>/</span><strong>{view === 'projects' ? '我的项目' : view === 'close-reading' ? '逐段精读' : active?.title || '工作台'}</strong></div><div className="top-actions"><div className="sync-dot"><span className="dot"></span>已同步</div><button className="icon-btn" aria-label="搜索" onClick={() => setNotice({ type: 'info', text: '搜索会在项目超过 3 个后自动启用' })}><Search size={18} /></button><button className="create-btn" onClick={() => setShowCreate(true)}><Plus size={17} />新建项目</button></div></header>
      {notice && <div className={`notice ${notice.type}`} role="status"><span>{notice.type === 'error' ? <CloudOff size={16} /> : notice.type === 'success' ? <Cloud size={16} /> : <Sparkles size={16} />}</span>{notice.text}<button onClick={() => setNotice(null)} aria-label="关闭提示"><X size={15} /></button></div>}
      {loading ? <LoadingState /> : view === 'close-reading' ? <CloseReading /> : view === 'projects' ? <ProjectsView projects={projects} activeId={activeId} onSelect={selectProject} onCreate={() => setShowCreate(true)} /> : <Workspace project={active} onUpdate={updateProject} onNotice={setNotice} />}
    </main>
    {showCreate && <CreateProjectModal onClose={() => setShowCreate(false)} onCreated={handleCreated} onError={error => setNotice({ type: 'error', text: error.message })} />}
  </div>
}

function LoadingState() { return <div className="loading-state"><div className="spinner"></div><span>正在唤醒你的故事宇宙…</span></div> }

function ProjectsView({ projects, activeId, onSelect, onCreate }) { return <section className="page-section projects-page"><div className="page-heading"><div><span className="eyebrow">PROJECTS / 01</span><h1>我的项目</h1><p>所有故事，都从一个被命名的世界开始。</p></div><button className="primary-btn" onClick={onCreate}><Plus size={17} />创建项目</button></div>{projects.length === 0 ? <EmptyState onCreate={onCreate} /> : <div className="project-grid">{projects.map(project => <ProjectCard key={project.id} project={project} active={project.id === activeId} onClick={() => onSelect(project.id)} />)}</div>}</section> }
function ProjectCard({ project, active, onClick }) { return <button className={`project-card ${active ? 'selected' : ''}`} onClick={onClick}><div className="card-cover">{project.cover?.value ? <img src={project.cover.value} alt="" onError={e => { e.currentTarget.style.display = 'none'; e.currentTarget.parentElement.classList.add('cover-fallback') }} /> : <div className="cover-fallback"><BookOpen size={28} /></div>}<span className="visibility-pill">{project.visibility === 'shared' ? <><Share2 size={12} />共享</> : <><LockKeyhole size={12} />私密</>}</span></div><div className="card-content"><div><h3>{project.title}</h3><p>{project.description || '还没有简介，给这个故事留下一句注脚。'}</p></div><div className="card-meta"><span>{project.draft?.content ? `${project.draft.content.length} 字草稿` : '空白草稿'}</span><span>{formatDate(project.updatedAt)}</span></div></div></button> }
function EmptyState({ onCreate }) { return <div className="empty-state"><div className="empty-icon"><Compass size={25} /></div><h2>还没有故事</h2><p>先给你的第一个世界一个名字，工作台会替你记住每次灵感。</p><button className="primary-btn" onClick={onCreate}><Plus size={17} />创建第一个项目</button></div> }

function Workspace({ project, onUpdate, onNotice }) { const [draft, setDraft] = useState(null); const [draftLoading, setDraftLoading] = useState(Boolean(project)); const [saveState, setSaveState] = useState('saved'); const [conflict, setConflict] = useState(null); const [showMeta, setShowMeta] = useState(false); const saveTimer = useRef(null); const latestDraft = useRef(null); const localKey = project ? `novelverse-draft-${project.id}` : null
  useEffect(() => { let cancelled = false; if (!project) { setDraft(null); setDraftLoading(false); return } setDraftLoading(true); api(`/projects/${project.id}/draft`).then(({ draft }) => { if (cancelled) return; const local = localKey ? localStorage.getItem(localKey) : null; const localDraft = local ? JSON.parse(local) : null; const localIsNewer = localDraft && (localDraft.version > draft.version || (localDraft.version === draft.version && localDraft.content !== draft.content)); const chosen = localIsNewer ? localDraft : draft; setDraft(chosen); latestDraft.current = chosen; setDraftLoading(false); if (localIsNewer) setSaveState('pending') }).catch(error => { if (!cancelled) { setDraft(project.draft); setDraftLoading(false); onNotice({ type: 'error', text: error.message }) } }); return () => { cancelled = true } }, [project?.id])
  const persist = useCallback(async (value, immediate = false) => { if (!project || !value) return; clearTimeout(saveTimer.current); const run = async () => { setSaveState('saving'); try { const result = await api(`/projects/${project.id}/draft`, { method: 'PUT', body: JSON.stringify({ content: value.content, baseVersion: value.version }) }); const next = result.draft; setDraft(next); latestDraft.current = next; localStorage.removeItem(localKey); setSaveState('saved'); onUpdate({ ...project, draft: next, updatedAt: next.updatedAt }) } catch (error) { if (error.error === 'DRAFT_CONFLICT') { setConflict(error); setSaveState('conflict') } else { localStorage.setItem(localKey, JSON.stringify(value)); setSaveState('failed') } } }; immediate ? run() : (saveTimer.current = setTimeout(run, 900)) }, [project, localKey, onUpdate])
  useEffect(() => { const onKey = event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 's') { event.preventDefault(); if (latestDraft.current) persist(latestDraft.current, true) } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [persist])
  useEffect(() => () => { clearTimeout(saveTimer.current); const value = latestDraft.current; if (value && project && navigator.sendBeacon) { const blob = new Blob([JSON.stringify({ content: value.content, baseVersion: value.version })], { type: 'application/json' }); navigator.sendBeacon(`${API}/projects/${project.id}/draft?userId=${encodeURIComponent(userId)}`, blob) } }, [project?.id])
  const onChange = event => { const next = { ...(draft || { version: project?.draft?.version || 0 }), content: event.target.value }; setDraft(next); latestDraft.current = next; setSaveState('pending'); localStorage.setItem(localKey, JSON.stringify(next)); persist(next) }
  const chooseConflict = choice => { if (choice === 'local') { setConflict(null); persist(draft, true) } else { const server = conflict.serverDraft; setDraft(server); latestDraft.current = server; localStorage.removeItem(localKey); setConflict(null); setSaveState('saved') } }
  if (!project) return <section className="page-section workspace-empty"><EmptyState /></section>
  return <section className="workspace"><div className="workspace-head"><div><span className="eyebrow">WORKSPACE / {project.visibility === 'shared' ? 'SHARED' : 'PRIVATE'}</span><h1>{project.title}</h1><p>{project.description || '给这个故事留下一句注脚。'}</p></div><div className="workspace-actions"><button className="secondary-btn" onClick={() => setShowMeta(value => !value)}><FilePenLine size={16} />编辑项目</button><button className="secondary-btn" onClick={() => onNotice({ type: 'info', text: project.visibility === 'shared' ? '已是共享项目，邀请入口即将开放' : '项目保持私密，只有你能看到' })}><Share2 size={16} />{project.visibility === 'shared' ? '共享中' : '共享'}</button></div></div>{showMeta && <ProjectMeta project={project} onUpdate={onUpdate} onClose={() => setShowMeta(false)} onNotice={onNotice} />}
    <div className="workspace-grid"><div className="editor-panel"><div className="editor-toolbar"><div className="editor-label"><span className="live-dot"></span>草稿 · 第一章</div><div className={`save-indicator ${saveState}`}><Save size={14} />{saveState === 'saving' ? '保存中…' : saveState === 'pending' ? '待保存' : saveState === 'failed' ? '保存失败，已暂存本地' : saveState === 'conflict' ? '存在版本冲突' : '已自动保存'}<button className="icon-btn tiny" onClick={() => draft && persist(draft, true)} aria-label="立即保存"><RefreshCw size={13} /></button></div></div>{draftLoading ? <div className="editor-loading"><div className="spinner small"></div>正在恢复最近编辑…</div> : <textarea className="draft-editor" value={draft?.content || ''} onChange={onChange} placeholder="从一句话开始，写下这个世界的第一束光…" aria-label="小说草稿编辑器" />}</div><aside className="insight-rail"><div className="rail-block"><span className="eyebrow">PROJECT NOTE</span><h3>让故事先呼吸</h3><p>不用急着写完。每一次自动保存，都是给未来的自己留一盏灯。</p><div className="rail-line"></div><div className="stat-row"><span>字数</span><strong>{draft?.content?.length || 0}</strong></div><div className="stat-row"><span>版本</span><strong>v{(draft?.version || 0) + 1}</strong></div></div><div className="rail-block muted-block"><div className="rail-icon"><Cloud size={17} /></div><div><strong>跨设备同步</strong><p>草稿会在你的设备间保持最新。</p></div></div></aside></div>{conflict && <ConflictBanner conflict={conflict} onChoose={chooseConflict} />}</section> }

function ProjectMeta({ project, onUpdate, onClose, onNotice }) { const [title, setTitle] = useState(project.title); const [description, setDescription] = useState(project.description); const [visibility, setVisibility] = useState(project.visibility); const submit = async event => { event.preventDefault(); try { const { project: updated } = await api(`/projects/${project.id}`, { method: 'PATCH', body: JSON.stringify({ title, description, visibility }) }); onUpdate(updated); onClose(); onNotice({ type: 'success', text: '项目资料已更新' }) } catch (error) { onNotice({ type: 'error', text: error.message }) } }; return <form className="meta-panel" onSubmit={submit}><div className="meta-fields"><label>项目标题<input value={title} onChange={e => setTitle(e.target.value)} required /></label><label>简介<input value={description} onChange={e => setDescription(e.target.value)} placeholder="一句话介绍你的故事" /></label><label>可见范围<select value={visibility} onChange={e => setVisibility(e.target.value)}><option value="private">私密 · 只有我</option><option value="shared">共享 · 邀请后可见</option></select></label></div><div className="meta-actions"><button type="button" className="text-btn" onClick={onClose}>取消</button><button type="submit" className="primary-btn">保存资料</button></div></form> }
function ConflictBanner({ conflict, onChoose }) { return <div className="conflict-banner"><div><strong>发现另一台设备的更新</strong><p>你可以保留当前草稿，或恢复服务器上最新的版本。</p></div><div className="conflict-actions"><button className="secondary-btn" onClick={() => onChoose('server')}>使用最新版本</button><button className="primary-btn" onClick={() => onChoose('local')}>保留我的版本</button></div></div> }

function CreateProjectModal({ onClose, onCreated, onError }) { const [form, setForm] = useState({ title: '', description: '', visibility: 'private', cover: null }); const [coverError, setCoverError] = useState(''); const [saving, setSaving] = useState(false); const update = (key, value) => setForm(state => ({ ...state, [key]: value })); const onCover = event => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) { setCoverError('封面需要是图片文件'); return } if (file.size > 4 * 1024 * 1024) { setCoverError('封面不能超过 4MB'); return } setCoverError(''); const reader = new FileReader(); reader.onload = () => update('cover', { kind: 'image', value: reader.result, name: file.name }); reader.readAsDataURL(file) }; const submit = async event => { event.preventDefault(); setSaving(true); try { const { project } = await api('/projects', { method: 'POST', body: JSON.stringify(form) }); onCreated(project) } catch (error) { onError(error) } finally { setSaving(false) } }; return <div className="modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="create-title"><div className="modal-header"><div><span className="eyebrow">NEW PROJECT / 01</span><h2 id="create-title">给故事一个名字</h2></div><button className="icon-btn" onClick={onClose} aria-label="关闭"><X size={19} /></button></div><form onSubmit={submit}><div className="cover-uploader"><div className="cover-preview">{form.cover?.value ? <img src={form.cover.value} alt="封面预览" /> : <><ImagePlus size={22} /><span>封面草稿</span></>}</div><div><label className="upload-btn"><ImagePlus size={15} />上传封面<input type="file" accept="image/png,image/jpeg,image/webp" onChange={onCover} /></label><p className="field-hint">PNG / JPG / WEBP，最大 4MB</p>{coverError && <p className="field-error">{coverError}</p>}</div></div><label>项目标题<span className="required">*</span><input autoFocus value={form.title} onChange={e => update('title', e.target.value)} placeholder="例如：盐与风的航线" required /></label><label>一句话简介<input value={form.description} onChange={e => update('description', e.target.value)} placeholder="这个故事会带你去哪里？" /></label><fieldset><legend>可见范围</legend><div className="visibility-options"><button type="button" className={form.visibility === 'private' ? 'selected' : ''} onClick={() => update('visibility', 'private')}><LockKeyhole size={16} /><span><strong>私密</strong><small>只有你能看到</small></span></button><button type="button" className={form.visibility === 'shared' ? 'selected' : ''} onClick={() => update('visibility', 'shared')}><Share2 size={16} /><span><strong>共享</strong><small>邀请后一起创作</small></span></button></div></fieldset><div className="modal-actions"><button type="button" className="text-btn" onClick={onClose}>稍后再说</button><button className="primary-btn" disabled={saving}>{saving ? '创建中…' : <><span>创建并开始写作</span><Send size={15} /></>}</button></div></form></div></div> }

createRoot(document.getElementById('root')).render(<App />)
